### ISSUE TITLE
We need a better way to construct API URLs than string concatenation.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/marketplace-content-tools#11]

**Comment by ngokevin** [comment]
Routes file at the root of each content type folder

**Comment by ngokevin** [comment]
Benefits for keeping the route within the action is portability and it's more componentized. 

Cons is that we can't see all of our routes in one place.

Or we can just use a small string lib to get rid of the use of urlJoin (e.g., url('/addon/:slug', [slug]))

**Comment by chuckharmston** [comment]
I'd rather see the routes in one place, I think. Or maybe expose them constants and import them in a central routes file? That seems a little convoluted.

**Comment by ngokevin** [comment]
I somewhat don't like my actions having outer dependencies on the app, the idea of being able to drop the actions into other projects if needed is nice since they're just pure functions. we could have the actions export them at least...but not sure if i want actions to import them
